function RiskCard({ riskLevel, riskScore }) {
  const getRiskClass = () => {
    switch (riskLevel) {
      case "LOW":
        return "risk-low";
      case "MEDIUM":
        return "risk-medium";
      case "HIGH":
        return "risk-high";
      case "CRITICAL":
        return "risk-critical";
      default:
        return "risk-unknown";
    }
  };

  const safeScore =
    typeof riskScore === "number"
      ? Math.min(Math.max(riskScore, 0), 100)
      : 0;

  return (
    <section className={`risk-card ${getRiskClass()}`}>
      <div className="risk-card-header">
        <div>
          <span className="risk-label">
            AI SECURITY ASSESSMENT
          </span>

          <h2>Security Risk Assessment</h2>
        </div>

        <span className="risk-badge">
          {riskLevel || "UNKNOWN"}
        </span>
      </div>

      <div className="risk-card-content">
        <div className="risk-score-container">
          <div className="risk-score">
            <span className="score-number">
              {safeScore}
            </span>

            <span className="score-label">
              / 100
            </span>
          </div>

          <p className="risk-score-description">
            Overall Risk Score
          </p>
        </div>

        <div className="risk-meter-container">
          <div className="risk-meter-header">
            <span>Risk Level</span>
            <span>{safeScore}%</span>
          </div>

          <div className="risk-meter">
            <div
              className="risk-meter-fill"
              style={{
                width: `${safeScore}%`
              }}
            ></div>
          </div>

          <div className="risk-meter-labels">
            <span>Low</span>
            <span>Medium</span>
            <span>High</span>
            <span>Critical</span>
          </div>
        </div>
      </div>

      <div className="risk-description">
        <strong>Assessment:</strong>

        <span>
          The risk score is generated by analyzing the
          reconnaissance information collected from the
          target.
        </span>
      </div>
    </section>
  );
}

export default RiskCard;